
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fabricio 
  password: PostgreSQL_Role_Password


development:
  <<: *default
  database: money_control_app_rails_development

  
test:
  <<: *default
  database: money_control_app_rails_test

production:
  <<: *default
  database: money_control_app_rails_production
  username: money_control_app_rails
  password: <%= ENV['MONEY_CONTROL_APP_RAILS_DATABASE_PASSWORD'] %>
